### ISSUE TITLE
`Operation failed` for images imported with `napari-aicsimageio` (xarray issue?)

### ISSUE THREAD

**Issue by psobolewskiPhD** [clEsperanto/napari_pyclesperanto_assistant#50]
This for sure used to work, because it was my normal work flow...but I'm not sure when it started to fail, because I've been swamped and away from the microscope for a number of months.
Anyhow, currently (napari 04.14, pyCL-assistant 0.15.3) doing `Background subtraction` gives an `Operation Failed` message and the following is printed for a LIF imported using `napari-aicsimageio` (doesn't matter whether in- or out-of-memory).

<details>

```
2022-02-17 21:30:03.554 | INFO     | napari_pyclesperanto_assistant._gui._category_widget:call_op:124 - cle.top_hat_box (clesperanto)(..., 10.0, 10.0, 0.0)
2022-02-17 21:30:03.588 | ERROR    | napari_pyclesperanto_assistant._gui._category_widget:gui_function:328 - An error has been caught in function 'gui_function', process 'MainProcess' (77252), thread 'MainThread' (4380247424):
Traceback (most recent call last):

  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/bin/napari", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x1135f8790>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari/__main__.py", line 449, in main
    _run()
    └ <function _run at 0x1135f85e0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari/__main__.py", line 338, in _run
    run(gui_exceptions=True)
    └ <function run at 0x1138d0a60>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari/_qt/qt_event_loop.py", line 402, in run
    app.exec_()
    │   └ <built-in method exec_>
    └ <PyQt5.QtWidgets.QApplication object at 0x114055dc0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari_pyclesperanto_assistant/_gui/_Assistant.py", line 171, in _on_item_clicked
    self._activate(CATEGORIES.get(item.text()))
    │    │         │          │   │    └ <built-in method text>
    │    │         │          │   └ <PyQt5.QtWidgets.QListWidgetItem object at 0x1507a1dc0>
    │    │         │          └ <method 'get' of 'dict' objects>
    │    │         └ {'Remove noise': Category(name='Removal noise', description='Remove noise from images, e.g. by local averaging and blurring.'...
    │    └ <function Assistant._activate at 0x132bc8c10>
    └ <napari_pyclesperanto_assistant._gui._Assistant.Assistant object at 0x119436af0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari_pyclesperanto_assistant/_gui/_Assistant.py", line 202, in _activate
    self._layers[gui()] = (dw, gui)
    │    │       │         │   └ <FunctionGui do_remove_background(*, input0: napari.layers.image.image.Image = <Image layer '0 :: A3 Region2_Merged' at 0x130...
    │    │       │         └ <napari._qt.widgets.qt_viewer_dock_widget.QtViewerDockWidget object at 0x1694bde50>
    │    │       └ <FunctionGui do_remove_background(*, input0: napari.layers.image.image.Image = <Image layer '0 :: A3 Region2_Merged' at 0x130...
    │    └ {}
    └ <napari_pyclesperanto_assistant._gui._Assistant.Assistant object at 0x119436af0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 303, in __call__
    value = self._function(*bound.args, **bound.kwargs)
            │    │          │     │       │     └ <property object at 0x10578e130>
            │    │          │     │       └ <BoundArguments (input0=<Image layer '0 :: A3 Region2_Merged' at 0x130d05670>, op_name='top_hat_box (clesperanto)', x=10.0, y...
            │    │          │     └ <property object at 0x10578e0e0>
            │    │          └ <BoundArguments (input0=<Image layer '0 :: A3 Region2_Merged' at 0x130d05670>, op_name='top_hat_box (clesperanto)', x=10.0, y...
            │    └ <function make_gui_for_category.<locals>.gui_function at 0x15023fee0>
            └ <FunctionGui do_remove_background(*, input0: napari.layers.image.image.Image = <Image layer '0 :: A3 Region2_Merged' at 0x130...
> File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari_pyclesperanto_assistant/_gui/_category_widget.py", line 328, in gui_function
    result, used_args = call_op(op_name, inputs, t_position, viewer, **kwargs)
                        │       │        │       │           │         └ {'x': 10.0, 'y': 10.0, 'z': 0.0, 'u': 0.0, 'v': 0.0, 'w': 0.0, 'a': False, 'b': False, 'c': False, 'k': '', 'l': '', 'm': ''}
                        │       │        │       │           └ Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 648.7615000...
                        │       │        │       └ None
                        │       │        └ [<Image layer '0 :: A3 Region2_Merged' at 0x130d05670>]
                        │       └ 'top_hat_box (clesperanto)'
                        └ <function call_op at 0x132bc81f0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari_pyclesperanto_assistant/_gui/_category_widget.py", line 126, in call_op
    gpu_out = cle_function(*args)
              │             └ (<xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (T: 1, C: 1,
              │                                                               ...
              └ <function top_hat_box at 0x132913e50>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_plugin_function.py", line 68, in worker_function
    bound.arguments[key] = output_creator(*bound.args[:len(sig2.parameters)])
    │     │         │      │               │     │         │    └ <property object at 0x10578e1d0>
    │     │         │      │               │     │         └ <Signature (*args)>
    │     │         │      │               │     └ <property object at 0x10578e0e0>
    │     │         │      │               └ <BoundArguments (input=<xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (T: 1, C: 1,
    │     │         │      │                                           ...
    │     │         │      └ <function create_like at 0x1322de940>
    │     │         └ 'destination'
    │     └ <member 'arguments' of 'BoundArguments' objects>
    └ <BoundArguments (input=<xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (T: 1, C: 1,
                                ...
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_create.py", line 32, in create_like
    return create(dimensions)
           │      └ <xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (T: 1, C: 1,
           │                                                         ...
           └ <function create at 0x1322de5e0>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_create.py", line 21, in create
    return Backend.get_instance().get().empty(dimensions, dtype)
           │       │                          │           └ <class 'numpy.float32'>
           │       │                          └ (<xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (C: 1, Z: 1,
           │       │                                                                            ...
           │       └ <classmethod object at 0x1322c0a90>
           └ <class 'pyclesperanto_prototype._tier0._backends.Backend'>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_opencl_backend.py", line 38, in empty
    return OCLArray(queue, shape, dtype)
           │        │      │      └ <class 'numpy.float32'>
           │        │      └ (<xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (C: 1, Z: 1,
           │        │                                                        ...
           │        └ <pyopencl._cl.CommandQueue object at 0x1312b0e50>
           └ <class 'pyclesperanto_prototype._tier0._pycl.OCLArray'>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/pyopencl/array.py", line 510, in __init__
    if dim < 0:
       └ <xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (C: 1, Z: 1,
                                                          ...
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/xarray/core/common.py", line 131, in __bool__
    return bool(self.values)
                │    └ <property object at 0x1214f29f0>
                └ <xarray.DataArray 'transpose-e7c3c82e071bba4debc777882416d09e' (C: 1, Z: 1,
                                                                   ...

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```
</details>

**Comment by haesleinhuepf** [comment]
That looks like a similar issue I had earlier with dask-arrays. I could fix that by converting xarray images to numpy images but therefore, I would need an example dataset. Can you share the file you were opening?

Could you also check if calling `Tools > Utilities > Convert to Numpy` helps? (as a workaround)

**Comment by psobolewskiPhD** [comment]
Converting to numpy works, but loses scale info—not impossible to deal with, but odd at first when the new layer is like 4x "bigger".
Also what's wierd is that importing a TIF via `napari-aicsimageio` also works and I would expect that to also be done via xarray.
Here's a LIF that I know used to work and isn't too huge:
https://www.icloud.com/iclouddrive/0a612NOXIVfYaYI07ILJH6LVQ#2021040_H33342_L929_24w_A3_tilescan
(also I can still run stardist-napari on the imported layer just as before, so whatever is happening seems to be semi-specific to pyclesperanto.)

**Comment by haesleinhuepf** [comment]
Hey Peter @psobolewskiPhD ,

I just about to fix this issue. I'll take some notes here, just in case you (or anybody else) would like to learn better how clesperanto internals work.

This works with an XArray `imageX`:
```
gpu_image = cle.push(imageX)
cle.gaussian_blur(gpu_image)
```

This doesn't:
```
cle.gaussian_blur(imageX)
```

Hence, we can push the image to the GPU, just the auto-push doesn't work. The image is not recognized as pushable, because the XArray image type is not in this list:

https://github.com/clEsperanto/pyclesperanto_prototype/blob/e80b3e2289ef43099459ded0766fdd1b0da1d679/pyclesperanto_prototype/_tier0/_types.py#L9

I'll release a fix in a minute.

**Comment by psobolewskiPhD** [comment]
Oh! I didn't even know there was auto-push functionality. Very sweet!
Also, FYI new version of `napari-aicsimageio` has been released, so the auto-squeeze is live:
https://github.com/AllenCellModeling/napari-aicsimageio/releases/tag/v0.5.0

**Comment by psobolewskiPhD** [comment]
Just installed the new pycles-prototype and now everything works like a charm!
🎉 
You're incredible @haesleinhuepf !!
❤️

**Comment by haesleinhuepf** [comment]
Thanks for testing so quickly @psobolewskiPhD !

**Comment by psobolewskiPhD** [comment]
GPU accelerated testing! 🚀
